### ISSUE TITLE
Increase total years teaching and years at school by 1

### ISSUE THREAD

**Issue by bguerrettaz** [AgriculturalEducation/Issues-Enhancements#1]
database, teacher profile, that Total Yrs teaching and Yrs at Current School increases by 1 for every teacher in the database

**Comment by DeanDittmar** [comment]
Complete by end of day on Sunday, 7-15-18, if possible.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by bguerrettaz** [comment]
Actual hours: 1

**Comment by DeanDittmar** [comment]
ok. confirmed.  completed. 7-15-18

**Comment by bguerrettaz** [comment]
Thanks.  Once you've confirmed everything, you can close the issue.  If you ever want to reopen you can find it and simply reopen it.

I'll close this one.  thanks
